# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Github checkout action | https://github.com/actions/checkout
      # Private repo checkout | https://github.com/actions/checkout/issues/116#issuecomment-644419389
      # Generate a PAT (personal access token) for your account, then add the PAT to repositories
      #   that need it (as a `secret`) to access other private repositories in your account for GitHub Action
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ZJ_REPO_PAT }}

      - name: Setup and run pre-commit
        run: bash ./scripts/zj-pre-commit.bash
